// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chord.proto

// Protobuf Java Version: 3.25.3
package dev.serathiuk.javadht.chord.grpc;

public final class ChordOuterClass {
  private ChordOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Node_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Node_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NodeData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NodeData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Entry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Entry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PutResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PutResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013chord.proto\".\n\004Node\022\n\n\002id\030\001 \001(\r\022\014\n\004hos" +
      "t\030\002 \001(\t\022\014\n\004port\030\003 \001(\r\"]\n\010NodeData\022\023\n\004nod" +
      "e\030\001 \001(\0132\005.Node\022\034\n\rnodeSuccessor\030\002 \001(\0132\005." +
      "Node\022\036\n\017nodePredecessor\030\003 \001(\0132\005.Node\"#\n\005" +
      "Entry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t\"\035\n\013Put" +
      "Response\022\016\n\006nodeId\030\001 \001(\r\"\031\n\nGetRequest\022\013" +
      "\n\003key\030\001 \001(\t\"9\n\013GetResponse\022\013\n\003key\030\001 \001(\t\022" +
      "\r\n\005value\030\002 \001(\t\022\016\n\006nodeId\030\003 \001(\004\"\007\n\005Empty2" +
      "\244\001\n\005Chord\022!\n\rfindSuccessor\022\005.Node\032\t.Node" +
      "Data\022\027\n\006notify\022\005.Node\032\006.Empty\022 \n\013getNode" +
      "Data\022\006.Empty\032\t.NodeData\022\033\n\003put\022\006.Entry\032\014" +
      ".PutResponse\022 \n\003get\022\013.GetRequest\032\014.GetRe" +
      "sponseB$\n dev.serathiuk.javadht.chord.gr" +
      "pcP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Node_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Node_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Node_descriptor,
        new java.lang.String[] { "Id", "Host", "Port", });
    internal_static_NodeData_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_NodeData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NodeData_descriptor,
        new java.lang.String[] { "Node", "NodeSuccessor", "NodePredecessor", });
    internal_static_Entry_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Entry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Entry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_PutResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_PutResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PutResponse_descriptor,
        new java.lang.String[] { "NodeId", });
    internal_static_GetRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_GetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetRequest_descriptor,
        new java.lang.String[] { "Key", });
    internal_static_GetResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_GetResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetResponse_descriptor,
        new java.lang.String[] { "Key", "Value", "NodeId", });
    internal_static_Empty_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
