// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chord.proto

// Protobuf Java Version: 3.25.3
package dev.serathiuk.javadht.chord.grpc;

public interface NodeDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:NodeData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Node node = 1;</code>
   * @return Whether the node field is set.
   */
  boolean hasNode();
  /**
   * <code>.Node node = 1;</code>
   * @return The node.
   */
  dev.serathiuk.javadht.chord.grpc.Node getNode();
  /**
   * <code>.Node node = 1;</code>
   */
  dev.serathiuk.javadht.chord.grpc.NodeOrBuilder getNodeOrBuilder();

  /**
   * <code>.Node nodeSuccessor = 2;</code>
   * @return Whether the nodeSuccessor field is set.
   */
  boolean hasNodeSuccessor();
  /**
   * <code>.Node nodeSuccessor = 2;</code>
   * @return The nodeSuccessor.
   */
  dev.serathiuk.javadht.chord.grpc.Node getNodeSuccessor();
  /**
   * <code>.Node nodeSuccessor = 2;</code>
   */
  dev.serathiuk.javadht.chord.grpc.NodeOrBuilder getNodeSuccessorOrBuilder();

  /**
   * <code>.Node nodePredecessor = 3;</code>
   * @return Whether the nodePredecessor field is set.
   */
  boolean hasNodePredecessor();
  /**
   * <code>.Node nodePredecessor = 3;</code>
   * @return The nodePredecessor.
   */
  dev.serathiuk.javadht.chord.grpc.Node getNodePredecessor();
  /**
   * <code>.Node nodePredecessor = 3;</code>
   */
  dev.serathiuk.javadht.chord.grpc.NodeOrBuilder getNodePredecessorOrBuilder();
}
