// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chord.proto

// Protobuf Java Version: 3.25.3
package dev.serathiuk.javadht.chord.grpc;

/**
 * Protobuf type {@code NodeData}
 */
public final class NodeData extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:NodeData)
    NodeDataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use NodeData.newBuilder() to construct.
  private NodeData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private NodeData() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new NodeData();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return dev.serathiuk.javadht.chord.grpc.ChordOuterClass.internal_static_NodeData_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return dev.serathiuk.javadht.chord.grpc.ChordOuterClass.internal_static_NodeData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            dev.serathiuk.javadht.chord.grpc.NodeData.class, dev.serathiuk.javadht.chord.grpc.NodeData.Builder.class);
  }

  private int bitField0_;
  public static final int NODE_FIELD_NUMBER = 1;
  private dev.serathiuk.javadht.chord.grpc.Node node_;
  /**
   * <code>.Node node = 1;</code>
   * @return Whether the node field is set.
   */
  @java.lang.Override
  public boolean hasNode() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.Node node = 1;</code>
   * @return The node.
   */
  @java.lang.Override
  public dev.serathiuk.javadht.chord.grpc.Node getNode() {
    return node_ == null ? dev.serathiuk.javadht.chord.grpc.Node.getDefaultInstance() : node_;
  }
  /**
   * <code>.Node node = 1;</code>
   */
  @java.lang.Override
  public dev.serathiuk.javadht.chord.grpc.NodeOrBuilder getNodeOrBuilder() {
    return node_ == null ? dev.serathiuk.javadht.chord.grpc.Node.getDefaultInstance() : node_;
  }

  public static final int NODESUCCESSOR_FIELD_NUMBER = 2;
  private dev.serathiuk.javadht.chord.grpc.Node nodeSuccessor_;
  /**
   * <code>.Node nodeSuccessor = 2;</code>
   * @return Whether the nodeSuccessor field is set.
   */
  @java.lang.Override
  public boolean hasNodeSuccessor() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.Node nodeSuccessor = 2;</code>
   * @return The nodeSuccessor.
   */
  @java.lang.Override
  public dev.serathiuk.javadht.chord.grpc.Node getNodeSuccessor() {
    return nodeSuccessor_ == null ? dev.serathiuk.javadht.chord.grpc.Node.getDefaultInstance() : nodeSuccessor_;
  }
  /**
   * <code>.Node nodeSuccessor = 2;</code>
   */
  @java.lang.Override
  public dev.serathiuk.javadht.chord.grpc.NodeOrBuilder getNodeSuccessorOrBuilder() {
    return nodeSuccessor_ == null ? dev.serathiuk.javadht.chord.grpc.Node.getDefaultInstance() : nodeSuccessor_;
  }

  public static final int NODEPREDECESSOR_FIELD_NUMBER = 3;
  private dev.serathiuk.javadht.chord.grpc.Node nodePredecessor_;
  /**
   * <code>.Node nodePredecessor = 3;</code>
   * @return Whether the nodePredecessor field is set.
   */
  @java.lang.Override
  public boolean hasNodePredecessor() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>.Node nodePredecessor = 3;</code>
   * @return The nodePredecessor.
   */
  @java.lang.Override
  public dev.serathiuk.javadht.chord.grpc.Node getNodePredecessor() {
    return nodePredecessor_ == null ? dev.serathiuk.javadht.chord.grpc.Node.getDefaultInstance() : nodePredecessor_;
  }
  /**
   * <code>.Node nodePredecessor = 3;</code>
   */
  @java.lang.Override
  public dev.serathiuk.javadht.chord.grpc.NodeOrBuilder getNodePredecessorOrBuilder() {
    return nodePredecessor_ == null ? dev.serathiuk.javadht.chord.grpc.Node.getDefaultInstance() : nodePredecessor_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getNode());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(2, getNodeSuccessor());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(3, getNodePredecessor());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getNode());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getNodeSuccessor());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getNodePredecessor());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof dev.serathiuk.javadht.chord.grpc.NodeData)) {
      return super.equals(obj);
    }
    dev.serathiuk.javadht.chord.grpc.NodeData other = (dev.serathiuk.javadht.chord.grpc.NodeData) obj;

    if (hasNode() != other.hasNode()) return false;
    if (hasNode()) {
      if (!getNode()
          .equals(other.getNode())) return false;
    }
    if (hasNodeSuccessor() != other.hasNodeSuccessor()) return false;
    if (hasNodeSuccessor()) {
      if (!getNodeSuccessor()
          .equals(other.getNodeSuccessor())) return false;
    }
    if (hasNodePredecessor() != other.hasNodePredecessor()) return false;
    if (hasNodePredecessor()) {
      if (!getNodePredecessor()
          .equals(other.getNodePredecessor())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasNode()) {
      hash = (37 * hash) + NODE_FIELD_NUMBER;
      hash = (53 * hash) + getNode().hashCode();
    }
    if (hasNodeSuccessor()) {
      hash = (37 * hash) + NODESUCCESSOR_FIELD_NUMBER;
      hash = (53 * hash) + getNodeSuccessor().hashCode();
    }
    if (hasNodePredecessor()) {
      hash = (37 * hash) + NODEPREDECESSOR_FIELD_NUMBER;
      hash = (53 * hash) + getNodePredecessor().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static dev.serathiuk.javadht.chord.grpc.NodeData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.serathiuk.javadht.chord.grpc.NodeData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.serathiuk.javadht.chord.grpc.NodeData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.serathiuk.javadht.chord.grpc.NodeData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.serathiuk.javadht.chord.grpc.NodeData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.serathiuk.javadht.chord.grpc.NodeData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.serathiuk.javadht.chord.grpc.NodeData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dev.serathiuk.javadht.chord.grpc.NodeData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static dev.serathiuk.javadht.chord.grpc.NodeData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static dev.serathiuk.javadht.chord.grpc.NodeData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static dev.serathiuk.javadht.chord.grpc.NodeData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dev.serathiuk.javadht.chord.grpc.NodeData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(dev.serathiuk.javadht.chord.grpc.NodeData prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code NodeData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:NodeData)
      dev.serathiuk.javadht.chord.grpc.NodeDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dev.serathiuk.javadht.chord.grpc.ChordOuterClass.internal_static_NodeData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dev.serathiuk.javadht.chord.grpc.ChordOuterClass.internal_static_NodeData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dev.serathiuk.javadht.chord.grpc.NodeData.class, dev.serathiuk.javadht.chord.grpc.NodeData.Builder.class);
    }

    // Construct using dev.serathiuk.javadht.chord.grpc.NodeData.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getNodeFieldBuilder();
        getNodeSuccessorFieldBuilder();
        getNodePredecessorFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      node_ = null;
      if (nodeBuilder_ != null) {
        nodeBuilder_.dispose();
        nodeBuilder_ = null;
      }
      nodeSuccessor_ = null;
      if (nodeSuccessorBuilder_ != null) {
        nodeSuccessorBuilder_.dispose();
        nodeSuccessorBuilder_ = null;
      }
      nodePredecessor_ = null;
      if (nodePredecessorBuilder_ != null) {
        nodePredecessorBuilder_.dispose();
        nodePredecessorBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return dev.serathiuk.javadht.chord.grpc.ChordOuterClass.internal_static_NodeData_descriptor;
    }

    @java.lang.Override
    public dev.serathiuk.javadht.chord.grpc.NodeData getDefaultInstanceForType() {
      return dev.serathiuk.javadht.chord.grpc.NodeData.getDefaultInstance();
    }

    @java.lang.Override
    public dev.serathiuk.javadht.chord.grpc.NodeData build() {
      dev.serathiuk.javadht.chord.grpc.NodeData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public dev.serathiuk.javadht.chord.grpc.NodeData buildPartial() {
      dev.serathiuk.javadht.chord.grpc.NodeData result = new dev.serathiuk.javadht.chord.grpc.NodeData(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(dev.serathiuk.javadht.chord.grpc.NodeData result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.node_ = nodeBuilder_ == null
            ? node_
            : nodeBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.nodeSuccessor_ = nodeSuccessorBuilder_ == null
            ? nodeSuccessor_
            : nodeSuccessorBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.nodePredecessor_ = nodePredecessorBuilder_ == null
            ? nodePredecessor_
            : nodePredecessorBuilder_.build();
        to_bitField0_ |= 0x00000004;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof dev.serathiuk.javadht.chord.grpc.NodeData) {
        return mergeFrom((dev.serathiuk.javadht.chord.grpc.NodeData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(dev.serathiuk.javadht.chord.grpc.NodeData other) {
      if (other == dev.serathiuk.javadht.chord.grpc.NodeData.getDefaultInstance()) return this;
      if (other.hasNode()) {
        mergeNode(other.getNode());
      }
      if (other.hasNodeSuccessor()) {
        mergeNodeSuccessor(other.getNodeSuccessor());
      }
      if (other.hasNodePredecessor()) {
        mergeNodePredecessor(other.getNodePredecessor());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getNodeFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getNodeSuccessorFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getNodePredecessorFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private dev.serathiuk.javadht.chord.grpc.Node node_;
    private com.google.protobuf.SingleFieldBuilderV3<
        dev.serathiuk.javadht.chord.grpc.Node, dev.serathiuk.javadht.chord.grpc.Node.Builder, dev.serathiuk.javadht.chord.grpc.NodeOrBuilder> nodeBuilder_;
    /**
     * <code>.Node node = 1;</code>
     * @return Whether the node field is set.
     */
    public boolean hasNode() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.Node node = 1;</code>
     * @return The node.
     */
    public dev.serathiuk.javadht.chord.grpc.Node getNode() {
      if (nodeBuilder_ == null) {
        return node_ == null ? dev.serathiuk.javadht.chord.grpc.Node.getDefaultInstance() : node_;
      } else {
        return nodeBuilder_.getMessage();
      }
    }
    /**
     * <code>.Node node = 1;</code>
     */
    public Builder setNode(dev.serathiuk.javadht.chord.grpc.Node value) {
      if (nodeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        node_ = value;
      } else {
        nodeBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.Node node = 1;</code>
     */
    public Builder setNode(
        dev.serathiuk.javadht.chord.grpc.Node.Builder builderForValue) {
      if (nodeBuilder_ == null) {
        node_ = builderForValue.build();
      } else {
        nodeBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.Node node = 1;</code>
     */
    public Builder mergeNode(dev.serathiuk.javadht.chord.grpc.Node value) {
      if (nodeBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          node_ != null &&
          node_ != dev.serathiuk.javadht.chord.grpc.Node.getDefaultInstance()) {
          getNodeBuilder().mergeFrom(value);
        } else {
          node_ = value;
        }
      } else {
        nodeBuilder_.mergeFrom(value);
      }
      if (node_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.Node node = 1;</code>
     */
    public Builder clearNode() {
      bitField0_ = (bitField0_ & ~0x00000001);
      node_ = null;
      if (nodeBuilder_ != null) {
        nodeBuilder_.dispose();
        nodeBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.Node node = 1;</code>
     */
    public dev.serathiuk.javadht.chord.grpc.Node.Builder getNodeBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getNodeFieldBuilder().getBuilder();
    }
    /**
     * <code>.Node node = 1;</code>
     */
    public dev.serathiuk.javadht.chord.grpc.NodeOrBuilder getNodeOrBuilder() {
      if (nodeBuilder_ != null) {
        return nodeBuilder_.getMessageOrBuilder();
      } else {
        return node_ == null ?
            dev.serathiuk.javadht.chord.grpc.Node.getDefaultInstance() : node_;
      }
    }
    /**
     * <code>.Node node = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        dev.serathiuk.javadht.chord.grpc.Node, dev.serathiuk.javadht.chord.grpc.Node.Builder, dev.serathiuk.javadht.chord.grpc.NodeOrBuilder> 
        getNodeFieldBuilder() {
      if (nodeBuilder_ == null) {
        nodeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            dev.serathiuk.javadht.chord.grpc.Node, dev.serathiuk.javadht.chord.grpc.Node.Builder, dev.serathiuk.javadht.chord.grpc.NodeOrBuilder>(
                getNode(),
                getParentForChildren(),
                isClean());
        node_ = null;
      }
      return nodeBuilder_;
    }

    private dev.serathiuk.javadht.chord.grpc.Node nodeSuccessor_;
    private com.google.protobuf.SingleFieldBuilderV3<
        dev.serathiuk.javadht.chord.grpc.Node, dev.serathiuk.javadht.chord.grpc.Node.Builder, dev.serathiuk.javadht.chord.grpc.NodeOrBuilder> nodeSuccessorBuilder_;
    /**
     * <code>.Node nodeSuccessor = 2;</code>
     * @return Whether the nodeSuccessor field is set.
     */
    public boolean hasNodeSuccessor() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.Node nodeSuccessor = 2;</code>
     * @return The nodeSuccessor.
     */
    public dev.serathiuk.javadht.chord.grpc.Node getNodeSuccessor() {
      if (nodeSuccessorBuilder_ == null) {
        return nodeSuccessor_ == null ? dev.serathiuk.javadht.chord.grpc.Node.getDefaultInstance() : nodeSuccessor_;
      } else {
        return nodeSuccessorBuilder_.getMessage();
      }
    }
    /**
     * <code>.Node nodeSuccessor = 2;</code>
     */
    public Builder setNodeSuccessor(dev.serathiuk.javadht.chord.grpc.Node value) {
      if (nodeSuccessorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        nodeSuccessor_ = value;
      } else {
        nodeSuccessorBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.Node nodeSuccessor = 2;</code>
     */
    public Builder setNodeSuccessor(
        dev.serathiuk.javadht.chord.grpc.Node.Builder builderForValue) {
      if (nodeSuccessorBuilder_ == null) {
        nodeSuccessor_ = builderForValue.build();
      } else {
        nodeSuccessorBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.Node nodeSuccessor = 2;</code>
     */
    public Builder mergeNodeSuccessor(dev.serathiuk.javadht.chord.grpc.Node value) {
      if (nodeSuccessorBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          nodeSuccessor_ != null &&
          nodeSuccessor_ != dev.serathiuk.javadht.chord.grpc.Node.getDefaultInstance()) {
          getNodeSuccessorBuilder().mergeFrom(value);
        } else {
          nodeSuccessor_ = value;
        }
      } else {
        nodeSuccessorBuilder_.mergeFrom(value);
      }
      if (nodeSuccessor_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.Node nodeSuccessor = 2;</code>
     */
    public Builder clearNodeSuccessor() {
      bitField0_ = (bitField0_ & ~0x00000002);
      nodeSuccessor_ = null;
      if (nodeSuccessorBuilder_ != null) {
        nodeSuccessorBuilder_.dispose();
        nodeSuccessorBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.Node nodeSuccessor = 2;</code>
     */
    public dev.serathiuk.javadht.chord.grpc.Node.Builder getNodeSuccessorBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getNodeSuccessorFieldBuilder().getBuilder();
    }
    /**
     * <code>.Node nodeSuccessor = 2;</code>
     */
    public dev.serathiuk.javadht.chord.grpc.NodeOrBuilder getNodeSuccessorOrBuilder() {
      if (nodeSuccessorBuilder_ != null) {
        return nodeSuccessorBuilder_.getMessageOrBuilder();
      } else {
        return nodeSuccessor_ == null ?
            dev.serathiuk.javadht.chord.grpc.Node.getDefaultInstance() : nodeSuccessor_;
      }
    }
    /**
     * <code>.Node nodeSuccessor = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        dev.serathiuk.javadht.chord.grpc.Node, dev.serathiuk.javadht.chord.grpc.Node.Builder, dev.serathiuk.javadht.chord.grpc.NodeOrBuilder> 
        getNodeSuccessorFieldBuilder() {
      if (nodeSuccessorBuilder_ == null) {
        nodeSuccessorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            dev.serathiuk.javadht.chord.grpc.Node, dev.serathiuk.javadht.chord.grpc.Node.Builder, dev.serathiuk.javadht.chord.grpc.NodeOrBuilder>(
                getNodeSuccessor(),
                getParentForChildren(),
                isClean());
        nodeSuccessor_ = null;
      }
      return nodeSuccessorBuilder_;
    }

    private dev.serathiuk.javadht.chord.grpc.Node nodePredecessor_;
    private com.google.protobuf.SingleFieldBuilderV3<
        dev.serathiuk.javadht.chord.grpc.Node, dev.serathiuk.javadht.chord.grpc.Node.Builder, dev.serathiuk.javadht.chord.grpc.NodeOrBuilder> nodePredecessorBuilder_;
    /**
     * <code>.Node nodePredecessor = 3;</code>
     * @return Whether the nodePredecessor field is set.
     */
    public boolean hasNodePredecessor() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.Node nodePredecessor = 3;</code>
     * @return The nodePredecessor.
     */
    public dev.serathiuk.javadht.chord.grpc.Node getNodePredecessor() {
      if (nodePredecessorBuilder_ == null) {
        return nodePredecessor_ == null ? dev.serathiuk.javadht.chord.grpc.Node.getDefaultInstance() : nodePredecessor_;
      } else {
        return nodePredecessorBuilder_.getMessage();
      }
    }
    /**
     * <code>.Node nodePredecessor = 3;</code>
     */
    public Builder setNodePredecessor(dev.serathiuk.javadht.chord.grpc.Node value) {
      if (nodePredecessorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        nodePredecessor_ = value;
      } else {
        nodePredecessorBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.Node nodePredecessor = 3;</code>
     */
    public Builder setNodePredecessor(
        dev.serathiuk.javadht.chord.grpc.Node.Builder builderForValue) {
      if (nodePredecessorBuilder_ == null) {
        nodePredecessor_ = builderForValue.build();
      } else {
        nodePredecessorBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.Node nodePredecessor = 3;</code>
     */
    public Builder mergeNodePredecessor(dev.serathiuk.javadht.chord.grpc.Node value) {
      if (nodePredecessorBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          nodePredecessor_ != null &&
          nodePredecessor_ != dev.serathiuk.javadht.chord.grpc.Node.getDefaultInstance()) {
          getNodePredecessorBuilder().mergeFrom(value);
        } else {
          nodePredecessor_ = value;
        }
      } else {
        nodePredecessorBuilder_.mergeFrom(value);
      }
      if (nodePredecessor_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.Node nodePredecessor = 3;</code>
     */
    public Builder clearNodePredecessor() {
      bitField0_ = (bitField0_ & ~0x00000004);
      nodePredecessor_ = null;
      if (nodePredecessorBuilder_ != null) {
        nodePredecessorBuilder_.dispose();
        nodePredecessorBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.Node nodePredecessor = 3;</code>
     */
    public dev.serathiuk.javadht.chord.grpc.Node.Builder getNodePredecessorBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getNodePredecessorFieldBuilder().getBuilder();
    }
    /**
     * <code>.Node nodePredecessor = 3;</code>
     */
    public dev.serathiuk.javadht.chord.grpc.NodeOrBuilder getNodePredecessorOrBuilder() {
      if (nodePredecessorBuilder_ != null) {
        return nodePredecessorBuilder_.getMessageOrBuilder();
      } else {
        return nodePredecessor_ == null ?
            dev.serathiuk.javadht.chord.grpc.Node.getDefaultInstance() : nodePredecessor_;
      }
    }
    /**
     * <code>.Node nodePredecessor = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        dev.serathiuk.javadht.chord.grpc.Node, dev.serathiuk.javadht.chord.grpc.Node.Builder, dev.serathiuk.javadht.chord.grpc.NodeOrBuilder> 
        getNodePredecessorFieldBuilder() {
      if (nodePredecessorBuilder_ == null) {
        nodePredecessorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            dev.serathiuk.javadht.chord.grpc.Node, dev.serathiuk.javadht.chord.grpc.Node.Builder, dev.serathiuk.javadht.chord.grpc.NodeOrBuilder>(
                getNodePredecessor(),
                getParentForChildren(),
                isClean());
        nodePredecessor_ = null;
      }
      return nodePredecessorBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:NodeData)
  }

  // @@protoc_insertion_point(class_scope:NodeData)
  private static final dev.serathiuk.javadht.chord.grpc.NodeData DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new dev.serathiuk.javadht.chord.grpc.NodeData();
  }

  public static dev.serathiuk.javadht.chord.grpc.NodeData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<NodeData>
      PARSER = new com.google.protobuf.AbstractParser<NodeData>() {
    @java.lang.Override
    public NodeData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<NodeData> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<NodeData> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public dev.serathiuk.javadht.chord.grpc.NodeData getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

