// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chord.proto

// Protobuf Java Version: 3.25.3
package dev.serathiuk.javadht.chord.grpc;

public interface PutResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PutResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 nodeId = 1;</code>
   * @return The nodeId.
   */
  int getNodeId();
}
